### ISSUE TITLE
True/False Pointer

### ISSUE THREAD

**Issue by KalikaKay** [golang/cwg#33]
It's a suggestion. I can't tell if this is on your list of things to do already.
I bet it's easy enough.
[Twitter Request](https://twitter.com/jessfraz/status/910886461133791233)

**Comment by dlsniper** [comment]
` new(true) ` or ` new(false) ` seem to solve the problem described in the tweet. Or do I misunderstand this?

**Comment by campoy** [comment]
hi friends,

this repo is only for community organization and outreach, your request is more suitable for the mailing list golang-nuts as a new proposal in the go repo.

PS: you could always define the function below and us `a(true)`
```go
func a(b bool) *bool { return &b }
```

**Comment by KalikaKay** [comment]
You're wrong on that one - considering what community outreach looks like, but hey; congratulations on that function you got. 

;)
