### ISSUE TITLE
binary.Read accepting os.File as first parameter as replacement for reader 

### ISSUE THREAD

**Issue by xinkiknix** [golang/cwg#39]
In following code:
_func ReadFile(filename string) (JPGFile, error) {
	jpgFile := JPGFile{}
	in, err := os.Open(filename)
	defer in.Close()
	if err != nil {
		return jpgFile, err
	}
	binary.Read(in, binary.LittleEndian, &jpgFile)
	return jpgFile, nil
}_

**binary.Read** accepts "in" (os.File) as a reader, but if I pass the file as a parameter to the function I get the correct error message that "in" is not a reader as defined in the documentation:   func Read(r **io.Reader**, order ByteOrder, data interface{}) error

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
