### ISSUE TITLE
go1.10?

### ISSUE THREAD

**Issue by xing1987** [golang/cwg#43]
when is golang 1.10 release party? please help

**Comment by danicat** [comment]
@cassandraoid shouldn't we create a deck/site/repo for the go 1.10 release party?

**Comment by dlsniper** [comment]
Please feel free to use https://talks.godoc.org/github.com/dlsniper/talks/2018/go-1.10-release-party/presentation.slide It's done in the spirit of the previous slides

**Comment by Pisush** [comment]
Added this https://github.com/golang/go/wiki/Go-1.10-Release-Party 10 days ago, but I just saw this issue. @xing1987 @danicat @cassandraoid - let's celebrate 🎉 
Thanks @dlsniper for the slides!
